---
title: "ESM 244 Lab 1"
author: "Bri Baker"
date: "1/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(sf)
library(tmap)
```

### Read in SF trees data

```{r}
trees <- read_csv(here("data", "sf_trees", "sf_trees.csv"))
```


### Basic wrangling reminders

find top 5 trees by legal status, wrangle, graph

```{r}
top_5_status <- trees %>% 
  count(legal_status) %>% 
  drop_na(legal_status) %>% 
  rename(tree_count = n) %>% 
  relocate(tree_count) %>% 
  slice_max(tree_count, n = 5)
```

### Graph of top 5

```{r}
ggplot(data = top_5_status, aes(x = fct_reorder(legal_status, tree_count), 
                                y = tree_count))+
  geom_col()+
  labs(x = "legal status", y = "tree count")+
  coord_flip()+
  theme_minimal()
  
```
### more ex

keep obs for blackwood acacia

```{r}
blackwood_acacia <- trees %>% 
  filter(str_detect(species, "Blackwood Acacia")) %>% 
  select(legal_status, date, latitude, longitude)

ggplot(blackwood_acacia, aes(x = longitude, y = latitude))+
  geom_point()
```


### seperate and unite

```{r}
sf_trees_sep <- trees %>% 
  separate(species, into = c("spp_scientific", "spp_common"), sep = "::")
```


```{r}
sf_trees_unite <- trees %>% 
  unite("id_status", tree_id:legal_status, sep = "___")
```


### Make maps of blackwood acacias

`st_as_sf()` to convert lat and long to spatial coordinates

```{r}
blackwood_acacia_sp <- blackwood_acacia %>% 
  drop_na(longitude, latitude) %>% 
  st_as_sf(coords = c("longitude", "latitude"))

st_crs(blackwood_acacia_sp) = 4326

ggplot(blackwood_acacia_sp)+
  geom_sf(color = "darkgreen")
```


## read in SF shapefile

```{r}
sf_map <- read_sf(here("data", "sf_map", "tl_2017_06075_roads.shp"))

st_transform(sf_map, 4326)

ggplot(data = sf_map) +
  geom_sf()

```


combine maps

```{r}
ggplot()+
  geom_sf(data = sf_map, size = 0.1, color = "darkgray") +
  geom_sf(data = blackwood_acacia_sp, color = "red", size = 0.5) +
theme_void()
```

interactive map

```{r}
tmap_mode("view")

tm_shape(blackwood_acacia_sp) +
  tm_dots()
```

